services:

  debian:
    build:
      context: ./mirror
    ports:
    - 80:80
    volumes:
    - ./mirror-data:/mirror
    - ./mirror-data/cache:/var/cache/nginx

  registry:
    image: registry:3.0.0
    environment:
      - REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
      - REGISTRY_PROXY_USERNAME=${DOCKER_HUB_USERNAME}
      - REGISTRY_PROXY_PASSWORD=${DOCKER_HUB_ACCESS_TOKEN}
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry
